### ISSUE TITLE
Validates and Relations

### ISSUE THREAD

**Issue by Stef1380** [Stef1380/WanderVan#8]
Add validates and relations (has_many, belongs_to)
User has_many vans 
User has_many bookings 
Van belongs_to user 
Van has_many bookings
Booking belongs_to user
Booking belongs_to Van

Validates: 
A user needs to have a user_first_name and a user_last_name
A user needs to have a location 

A van needs to have a brand 
A van needs to have a description, 
A van needs to have number of seats
A van needs to have a price between 50 et 300
A van needs to have one category 
A van needs to have a location 

A booking needs to have a status
A booking needs to have a start and end-date
A booking needs to have a total price

**Comment by Amine13m** [comment]
validation and key finish
